/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {AltTokenContract} from "./AltToken";
import {CampaignNFTContract} from "./CampaignNFT";
import {ERC165Contract} from "./ERC165";
import {ERC20Contract} from "./ERC20";
import {ERC721Contract} from "./ERC721";
import {ERC721URIStorageContract} from "./ERC721URIStorage";
import {IERC165Contract} from "./IERC165";
import {IERC20Contract} from "./IERC20";
import {IERC20MetadataContract} from "./IERC20Metadata";
import {IERC721Contract} from "./IERC721";
import {IERC721MetadataContract} from "./IERC721Metadata";
import {IERC721ReceiverContract} from "./IERC721Receiver";
import {MigrationsContract} from "./Migrations";
import {OwnableContract} from "./Ownable";
import {RadaTokenContract} from "./RadaToken";
import {StoreContract} from "./Store";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AltToken"): AltTokenContract;
      require(name: "CampaignNFT"): CampaignNFTContract;
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "ERC721URIStorage"): ERC721URIStorageContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "RadaToken"): RadaTokenContract;
      require(name: "Store"): StoreContract;
    }
  }
}

export {AltTokenContract, AltTokenInstance} from "./AltToken";
export {CampaignNFTContract, CampaignNFTInstance} from "./CampaignNFT";
export {ERC165Contract, ERC165Instance} from "./ERC165";
export {ERC20Contract, ERC20Instance} from "./ERC20";
export {ERC721Contract, ERC721Instance} from "./ERC721";
export {
  ERC721URIStorageContract,
  ERC721URIStorageInstance,
} from "./ERC721URIStorage";
export {IERC165Contract, IERC165Instance} from "./IERC165";
export {IERC20Contract, IERC20Instance} from "./IERC20";
export {IERC20MetadataContract, IERC20MetadataInstance} from "./IERC20Metadata";
export {IERC721Contract, IERC721Instance} from "./IERC721";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export {MigrationsContract, MigrationsInstance} from "./Migrations";
export {OwnableContract, OwnableInstance} from "./Ownable";
export {RadaTokenContract, RadaTokenInstance} from "./RadaToken";
export {StoreContract, StoreInstance} from "./Store";
