type Query {
  users: [User]
  user(id: String!): User
}

type Mutation {
  createUser(req: CreateUserRequest): User
}

type User {
  id: String
  name: String
  campaigns: [Campaign!]
}

type Campaign {
  id: String
  name: String
  user: User
}

input CreateUserRequest {
  name: String
}
