type Query {
  campaigns: [Campaign]
  campaign(id: String!): Campaign
}

type Mutation {
  createCampaign(req: CreateCampaignRequest): Campaign
}

type User {
  id: String
  name: String
  campaigns: [Campaign!]
}

type Campaign {
  id: String
  name: String
  user: User
}

input CreateCampaignRequest {
  name: String
  userId: Int!
}
