# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: action-yarn-frontend
      uses: comchangs/action-yarn@v0.1-beta
      working-directory: ./frontend
      run: yarn build
    - name: action-yarn-backend
      uses: comchangs/action-yarn@v0.1-beta
      working-directory: ./backend
      run: yarn build
